print("Enter the two numbers and show the sum of given numbers")
print("Enter First Number: ", end='')
nm1 = input()
print("Enter Second Number: ", end='')
nm2 = input()
print("Sum of Two number is:- ",int(nm1)+int(nm2))

print("\n")
print("Enter the two numbers and show the multiplication")
print("Enter First number: ", end='')
nm1 = input()
print("Enter Second number: ", end='')
nm2 = input()
print("Multiplication of two numbers is:- ", int(nm1)*int(nm2))

print("\n")
print("Enter the two numbers and show the subtraction of numbers")
print("Enter First number: ", end='')
nm1 = input()
print("Enter Second number: ", end='')
nm2 = input()
print("Subtraction of two numbers :- ", int(nm1)-int(nm2))

print("\n")
print("Enter the two numbers and show the Division of numbers")
print("Enter First number: ", end='')
nm1 = input()
print("Enter Second number: ", end='')
nm2 = input()
print("Division of two numbers :- ", int(nm1)/int(nm2))