# -*- coding: utf-8 -*-

{
    'name': 'Dairy Shop',
    'version': '2.0.0',
    'summary': 'Third module of dairy',
    'sequence': -100,
    'description': """This is a second Dairy Shop""",
    'category': '',
    'author': "Intechual Solutions",
    'website': '',
    'images': [],
    'depends': ['mail','base','website','website_sale'],
    'data': [
        'security/ir.model.access.csv',
        # 'data/ir_cron_customer_email.xml',
        # 'data/dairy_admin_mail_template.xml',
        # 'data/dairy_customer_mail_template.xml',
        'data/sequence_dairy_order.xml',
        'views/dairy_menu.xml',
        'views/dairy_seller_view.xml',
        'views/dairy_buyer_view.xml',
        'views/dairy_res_partner_view.xml',
        'views/res_config_settings_views.xml',
        'views/website_template_inherit_view.xml',
        'report/ir_actions_dairy_report.xml',
        'report/ir_actions_dairy_admin_report_template.xml',
        'report/ir_actions_dairy_customer_report_template.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'assets': {},
    'license': 'LGPL-3',
}
